global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "gateway"
    static_configs:
      - targets: ['gateway:8080']

  - job_name: "file_service"
    static_configs:
      - targets: ['file_service:9081']

  - job_name: "post_service"
    static_configs:
      - targets: ['post_service:9082']

  - job_name: "user_service"
    static_configs:
      - targets: ['user_service:9083']

  - job_name: "messenger_service"
    static_configs:
      - targets: ['messenger_service:9084']

  - job_name: "feedback_service"
    static_configs:
      - targets: ['feedback_service:9085']

  - job_name: "friends_service"
    static_configs:
      - targets: ['friends_service:9086']

  - job_name: "community_service"
    static_configs:
      - targets: ['community_service:9087']

  - job_name: "prometheus"
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']
