services:
  backend:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: quickflow_backend
    volumes:
      - ../deploy:/quickflow_app/deploy  # Монтируем всю папку deploy целиком
    ports:
      - "8080:8080"
    depends_on:
      minio:
        condition: service_healthy
      postgres:
        condition: service_started
      redis:
        condition: service_started
    restart: always
    env_file:
      - .env

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: quickflow_admin
      POSTGRES_PASSWORD: SuperSecurePassword1
      POSTGRES_DB: quickflow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../deploy/sql:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./config/redis/redis.conf:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf"]

  # s3 хранилище minio
  minio:
    image: 'bitnami/minio:latest'
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 10s
      timeout: 10s
      retries: 3
    volumes:
      - minio_data:/data
      - minio_config:/root/.minio
    env_file:
      - .env

volumes:
  postgres_data:
  redis_data:
  minio_data:
  minio_config:
