allowed_origins = ["https://www.quickflowapp.ru"]
allowed_methos = ["GET", "POST", "DELETE"]
allowed_headers = ["Cookie", "Content-Type", "X-CSRF-Token"]
exposed_headers = ["Content-Type", "X-CSRF-Token"]
allow_credentials = true
options_passthrough = true
debug = true

