// Code generated by MockGen. DO NOT EDIT.
// Source: .//messenger_service/internal/usecase/message-usecase.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "quickflow/shared/models"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockMessageRepository is a mock of MessageRepository interface.
type MockMessageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMessageRepositoryMockRecorder
}

// MockMessageRepositoryMockRecorder is the mock recorder for MockMessageRepository.
type MockMessageRepositoryMockRecorder struct {
	mock *MockMessageRepository
}

// NewMockMessageRepository creates a new mock instance.
func NewMockMessageRepository(ctrl *gomock.Controller) *MockMessageRepository {
	mock := &MockMessageRepository{ctrl: ctrl}
	mock.recorder = &MockMessageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageRepository) EXPECT() *MockMessageRepositoryMockRecorder {
	return m.recorder
}

// DeleteMessage mocks base method.
func (m *MockMessageRepository) DeleteMessage(ctx context.Context, messageId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMessage", ctx, messageId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMessage indicates an expected call of DeleteMessage.
func (mr *MockMessageRepositoryMockRecorder) DeleteMessage(ctx, messageId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMessage", reflect.TypeOf((*MockMessageRepository)(nil).DeleteMessage), ctx, messageId)
}

// GetLastChatMessage mocks base method.
func (m *MockMessageRepository) GetLastChatMessage(ctx context.Context, chatId uuid.UUID) (*models.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastChatMessage", ctx, chatId)
	ret0, _ := ret[0].(*models.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastChatMessage indicates an expected call of GetLastChatMessage.
func (mr *MockMessageRepositoryMockRecorder) GetLastChatMessage(ctx, chatId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastChatMessage", reflect.TypeOf((*MockMessageRepository)(nil).GetLastChatMessage), ctx, chatId)
}

// GetLastReadTs mocks base method.
func (m *MockMessageRepository) GetLastReadTs(ctx context.Context, chatId, userId uuid.UUID) (*time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastReadTs", ctx, chatId, userId)
	ret0, _ := ret[0].(*time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastReadTs indicates an expected call of GetLastReadTs.
func (mr *MockMessageRepositoryMockRecorder) GetLastReadTs(ctx, chatId, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastReadTs", reflect.TypeOf((*MockMessageRepository)(nil).GetLastReadTs), ctx, chatId, userId)
}

// GetMessageById mocks base method.
func (m *MockMessageRepository) GetMessageById(ctx context.Context, messageId uuid.UUID) (models.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageById", ctx, messageId)
	ret0, _ := ret[0].(models.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessageById indicates an expected call of GetMessageById.
func (mr *MockMessageRepositoryMockRecorder) GetMessageById(ctx, messageId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageById", reflect.TypeOf((*MockMessageRepository)(nil).GetMessageById), ctx, messageId)
}

// GetMessagesForChatOlder mocks base method.
func (m *MockMessageRepository) GetMessagesForChatOlder(ctx context.Context, chatId uuid.UUID, numMessages int, timestamp time.Time) ([]models.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessagesForChatOlder", ctx, chatId, numMessages, timestamp)
	ret0, _ := ret[0].([]models.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessagesForChatOlder indicates an expected call of GetMessagesForChatOlder.
func (mr *MockMessageRepositoryMockRecorder) GetMessagesForChatOlder(ctx, chatId, numMessages, timestamp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessagesForChatOlder", reflect.TypeOf((*MockMessageRepository)(nil).GetMessagesForChatOlder), ctx, chatId, numMessages, timestamp)
}

// GetNumUnreadMessages mocks base method.
func (m *MockMessageRepository) GetNumUnreadMessages(ctx context.Context, chatId, userId uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNumUnreadMessages", ctx, chatId, userId)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNumUnreadMessages indicates an expected call of GetNumUnreadMessages.
func (mr *MockMessageRepositoryMockRecorder) GetNumUnreadMessages(ctx, chatId, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNumUnreadMessages", reflect.TypeOf((*MockMessageRepository)(nil).GetNumUnreadMessages), ctx, chatId, userId)
}

// SaveMessage mocks base method.
func (m *MockMessageRepository) SaveMessage(ctx context.Context, message models.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMessage", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveMessage indicates an expected call of SaveMessage.
func (mr *MockMessageRepositoryMockRecorder) SaveMessage(ctx, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMessage", reflect.TypeOf((*MockMessageRepository)(nil).SaveMessage), ctx, message)
}

// UpdateLastReadTs mocks base method.
func (m *MockMessageRepository) UpdateLastReadTs(ctx context.Context, timestamp time.Time, chatId, userId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastReadTs", ctx, timestamp, chatId, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastReadTs indicates an expected call of UpdateLastReadTs.
func (mr *MockMessageRepositoryMockRecorder) UpdateLastReadTs(ctx, timestamp, chatId, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastReadTs", reflect.TypeOf((*MockMessageRepository)(nil).UpdateLastReadTs), ctx, timestamp, chatId, userId)
}

// MockMessageValidator is a mock of MessageValidator interface.
type MockMessageValidator struct {
	ctrl     *gomock.Controller
	recorder *MockMessageValidatorMockRecorder
}

// MockMessageValidatorMockRecorder is the mock recorder for MockMessageValidator.
type MockMessageValidatorMockRecorder struct {
	mock *MockMessageValidator
}

// NewMockMessageValidator creates a new mock instance.
func NewMockMessageValidator(ctrl *gomock.Controller) *MockMessageValidator {
	mock := &MockMessageValidator{ctrl: ctrl}
	mock.recorder = &MockMessageValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageValidator) EXPECT() *MockMessageValidatorMockRecorder {
	return m.recorder
}

// ValidateMessage mocks base method.
func (m *MockMessageValidator) ValidateMessage(message models.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateMessage", message)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateMessage indicates an expected call of ValidateMessage.
func (mr *MockMessageValidatorMockRecorder) ValidateMessage(message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateMessage", reflect.TypeOf((*MockMessageValidator)(nil).ValidateMessage), message)
}
