// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package forms

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson8ceb9162DecodeQuickflowGatewayInternalDeliveryHttpForms(in *jlexer.Lexer, out *MessageAttachmentForm) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "media":
			if in.IsNull() {
				in.Skip()
				out.MediaURLs = nil
			} else {
				in.Delim('[')
				if out.MediaURLs == nil {
					if !in.IsDelim(']') {
						out.MediaURLs = make([]string, 0, 4)
					} else {
						out.MediaURLs = []string{}
					}
				} else {
					out.MediaURLs = (out.MediaURLs)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					v1 = string(in.String())
					out.MediaURLs = append(out.MediaURLs, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "audio":
			if in.IsNull() {
				in.Skip()
				out.AudioURLs = nil
			} else {
				in.Delim('[')
				if out.AudioURLs == nil {
					if !in.IsDelim(']') {
						out.AudioURLs = make([]string, 0, 4)
					} else {
						out.AudioURLs = []string{}
					}
				} else {
					out.AudioURLs = (out.AudioURLs)[:0]
				}
				for !in.IsDelim(']') {
					var v2 string
					v2 = string(in.String())
					out.AudioURLs = append(out.AudioURLs, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "files":
			if in.IsNull() {
				in.Skip()
				out.FileURLs = nil
			} else {
				in.Delim('[')
				if out.FileURLs == nil {
					if !in.IsDelim(']') {
						out.FileURLs = make([]string, 0, 4)
					} else {
						out.FileURLs = []string{}
					}
				} else {
					out.FileURLs = (out.FileURLs)[:0]
				}
				for !in.IsDelim(']') {
					var v3 string
					v3 = string(in.String())
					out.FileURLs = append(out.FileURLs, v3)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "stickers":
			if in.IsNull() {
				in.Skip()
				out.StickerURLs = nil
			} else {
				in.Delim('[')
				if out.StickerURLs == nil {
					if !in.IsDelim(']') {
						out.StickerURLs = make([]string, 0, 4)
					} else {
						out.StickerURLs = []string{}
					}
				} else {
					out.StickerURLs = (out.StickerURLs)[:0]
				}
				for !in.IsDelim(']') {
					var v4 string
					v4 = string(in.String())
					out.StickerURLs = append(out.StickerURLs, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8ceb9162EncodeQuickflowGatewayInternalDeliveryHttpForms(out *jwriter.Writer, in MessageAttachmentForm) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"media\":"
		out.RawString(prefix[1:])
		if in.MediaURLs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.MediaURLs {
				if v5 > 0 {
					out.RawByte(',')
				}
				out.String(string(v6))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"audio\":"
		out.RawString(prefix)
		if in.AudioURLs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v7, v8 := range in.AudioURLs {
				if v7 > 0 {
					out.RawByte(',')
				}
				out.String(string(v8))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"files\":"
		out.RawString(prefix)
		if in.FileURLs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v9, v10 := range in.FileURLs {
				if v9 > 0 {
					out.RawByte(',')
				}
				out.String(string(v10))
			}
			out.RawByte(']')
		}
	}
	if len(in.StickerURLs) != 0 {
		const prefix string = ",\"stickers\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v11, v12 := range in.StickerURLs {
				if v11 > 0 {
					out.RawByte(',')
				}
				out.String(string(v12))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MessageAttachmentForm) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8ceb9162EncodeQuickflowGatewayInternalDeliveryHttpForms(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MessageAttachmentForm) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8ceb9162EncodeQuickflowGatewayInternalDeliveryHttpForms(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MessageAttachmentForm) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8ceb9162DecodeQuickflowGatewayInternalDeliveryHttpForms(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MessageAttachmentForm) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8ceb9162DecodeQuickflowGatewayInternalDeliveryHttpForms(l, v)
}
