// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package forms

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson3ecd3d11DecodeQuickflowGatewayInternalDeliveryHttpForms(in *jlexer.Lexer, out *SearchForm) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "string":
			out.ToSearch = string(in.String())
		case "count":
			out.Count = uint(in.Uint())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3ecd3d11EncodeQuickflowGatewayInternalDeliveryHttpForms(out *jwriter.Writer, in SearchForm) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"string\":"
		out.RawString(prefix[1:])
		out.String(string(in.ToSearch))
	}
	{
		const prefix string = ",\"count\":"
		out.RawString(prefix)
		out.Uint(uint(in.Count))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SearchForm) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3ecd3d11EncodeQuickflowGatewayInternalDeliveryHttpForms(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SearchForm) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3ecd3d11EncodeQuickflowGatewayInternalDeliveryHttpForms(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SearchForm) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3ecd3d11DecodeQuickflowGatewayInternalDeliveryHttpForms(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SearchForm) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3ecd3d11DecodeQuickflowGatewayInternalDeliveryHttpForms(l, v)
}
