// Code generated by MockGen. DO NOT EDIT.
// Source: ./messenger_service/internal/delivery/grpc/message_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "quickflow/shared/models"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockMessageUseCase is a mock of MessageUseCase interface.
type MockMessageUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockMessageUseCaseMockRecorder
}

// MockMessageUseCaseMockRecorder is the mock recorder for MockMessageUseCase.
type MockMessageUseCaseMockRecorder struct {
	mock *MockMessageUseCase
}

// NewMockMessageUseCase creates a new mock instance.
func NewMockMessageUseCase(ctrl *gomock.Controller) *MockMessageUseCase {
	mock := &MockMessageUseCase{ctrl: ctrl}
	mock.recorder = &MockMessageUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageUseCase) EXPECT() *MockMessageUseCaseMockRecorder {
	return m.recorder
}

// DeleteMessage mocks base method.
func (m *MockMessageUseCase) DeleteMessage(ctx context.Context, messageId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMessage", ctx, messageId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMessage indicates an expected call of DeleteMessage.
func (mr *MockMessageUseCaseMockRecorder) DeleteMessage(ctx, messageId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMessage", reflect.TypeOf((*MockMessageUseCase)(nil).DeleteMessage), ctx, messageId)
}

// GetLastReadTs mocks base method.
func (m *MockMessageUseCase) GetLastReadTs(ctx context.Context, chatId, userId uuid.UUID) (*time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastReadTs", ctx, chatId, userId)
	ret0, _ := ret[0].(*time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastReadTs indicates an expected call of GetLastReadTs.
func (mr *MockMessageUseCaseMockRecorder) GetLastReadTs(ctx, chatId, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastReadTs", reflect.TypeOf((*MockMessageUseCase)(nil).GetLastReadTs), ctx, chatId, userId)
}

// GetMessageById mocks base method.
func (m *MockMessageUseCase) GetMessageById(ctx context.Context, messageId uuid.UUID) (models.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageById", ctx, messageId)
	ret0, _ := ret[0].(models.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessageById indicates an expected call of GetMessageById.
func (mr *MockMessageUseCaseMockRecorder) GetMessageById(ctx, messageId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageById", reflect.TypeOf((*MockMessageUseCase)(nil).GetMessageById), ctx, messageId)
}

// GetMessagesForChatOlder mocks base method.
func (m *MockMessageUseCase) GetMessagesForChatOlder(ctx context.Context, chatId, userId uuid.UUID, numMessages int, timestamp time.Time) ([]models.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessagesForChatOlder", ctx, chatId, userId, numMessages, timestamp)
	ret0, _ := ret[0].([]models.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessagesForChatOlder indicates an expected call of GetMessagesForChatOlder.
func (mr *MockMessageUseCaseMockRecorder) GetMessagesForChatOlder(ctx, chatId, userId, numMessages, timestamp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessagesForChatOlder", reflect.TypeOf((*MockMessageUseCase)(nil).GetMessagesForChatOlder), ctx, chatId, userId, numMessages, timestamp)
}

// GetNumUnreadMessages mocks base method.
func (m *MockMessageUseCase) GetNumUnreadMessages(ctx context.Context, chatId, userId uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNumUnreadMessages", ctx, chatId, userId)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNumUnreadMessages indicates an expected call of GetNumUnreadMessages.
func (mr *MockMessageUseCaseMockRecorder) GetNumUnreadMessages(ctx, chatId, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNumUnreadMessages", reflect.TypeOf((*MockMessageUseCase)(nil).GetNumUnreadMessages), ctx, chatId, userId)
}

// SaveMessage mocks base method.
func (m *MockMessageUseCase) SaveMessage(ctx context.Context, message models.Message) (*models.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMessage", ctx, message)
	ret0, _ := ret[0].(*models.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveMessage indicates an expected call of SaveMessage.
func (mr *MockMessageUseCaseMockRecorder) SaveMessage(ctx, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMessage", reflect.TypeOf((*MockMessageUseCase)(nil).SaveMessage), ctx, message)
}

// UpdateLastReadTs mocks base method.
func (m *MockMessageUseCase) UpdateLastReadTs(ctx context.Context, timestamp time.Time, chatId, userId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastReadTs", ctx, timestamp, chatId, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastReadTs indicates an expected call of UpdateLastReadTs.
func (mr *MockMessageUseCaseMockRecorder) UpdateLastReadTs(ctx, timestamp, chatId, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastReadTs", reflect.TypeOf((*MockMessageUseCase)(nil).UpdateLastReadTs), ctx, timestamp, chatId, userId)
}
