// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.7
// source: feedback_service.proto

package feedback

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FeedbackType int32

const (
	FeedbackType_FEEDBACK_GENERAL         FeedbackType = 0
	FeedbackType_FEEDBACK_POST            FeedbackType = 1
	FeedbackType_FEEDBACK_MESSENGER       FeedbackType = 2
	FeedbackType_FEEDBACK_RECOMMENDATIONS FeedbackType = 3
	FeedbackType_FEEDBACK_PROFILE         FeedbackType = 4
	FeedbackType_FEEDBACK_AUTH            FeedbackType = 5
)

// Enum value maps for FeedbackType.
var (
	FeedbackType_name = map[int32]string{
		0: "FEEDBACK_GENERAL",
		1: "FEEDBACK_POST",
		2: "FEEDBACK_MESSENGER",
		3: "FEEDBACK_RECOMMENDATIONS",
		4: "FEEDBACK_PROFILE",
		5: "FEEDBACK_AUTH",
	}
	FeedbackType_value = map[string]int32{
		"FEEDBACK_GENERAL":         0,
		"FEEDBACK_POST":            1,
		"FEEDBACK_MESSENGER":       2,
		"FEEDBACK_RECOMMENDATIONS": 3,
		"FEEDBACK_PROFILE":         4,
		"FEEDBACK_AUTH":            5,
	}
)

func (x FeedbackType) Enum() *FeedbackType {
	p := new(FeedbackType)
	*p = x
	return p
}

func (x FeedbackType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FeedbackType) Descriptor() protoreflect.EnumDescriptor {
	return file_feedback_service_proto_enumTypes[0].Descriptor()
}

func (FeedbackType) Type() protoreflect.EnumType {
	return &file_feedback_service_proto_enumTypes[0]
}

func (x FeedbackType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FeedbackType.Descriptor instead.
func (FeedbackType) EnumDescriptor() ([]byte, []int) {
	return file_feedback_service_proto_rawDescGZIP(), []int{0}
}

type Feedback struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Rating        int32                  `protobuf:"varint,2,opt,name=rating,proto3" json:"rating,omitempty"`
	RespondentId  string                 `protobuf:"bytes,3,opt,name=respondent_id,json=respondentId,proto3" json:"respondent_id,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Type          FeedbackType           `protobuf:"varint,5,opt,name=type,proto3,enum=file_service.FeedbackType" json:"type,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Feedback) Reset() {
	*x = Feedback{}
	mi := &file_feedback_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Feedback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Feedback) ProtoMessage() {}

func (x *Feedback) ProtoReflect() protoreflect.Message {
	mi := &file_feedback_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Feedback.ProtoReflect.Descriptor instead.
func (*Feedback) Descriptor() ([]byte, []int) {
	return file_feedback_service_proto_rawDescGZIP(), []int{0}
}

func (x *Feedback) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Feedback) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Feedback) GetRespondentId() string {
	if x != nil {
		return x.RespondentId
	}
	return ""
}

func (x *Feedback) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Feedback) GetType() FeedbackType {
	if x != nil {
		return x.Type
	}
	return FeedbackType_FEEDBACK_GENERAL
}

func (x *Feedback) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type AverageStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedbackId    string                 `protobuf:"bytes,1,opt,name=feedback_id,json=feedbackId,proto3" json:"feedback_id,omitempty"`
	Average       float32                `protobuf:"fixed32,2,opt,name=average,proto3" json:"average,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AverageStat) Reset() {
	*x = AverageStat{}
	mi := &file_feedback_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AverageStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AverageStat) ProtoMessage() {}

func (x *AverageStat) ProtoReflect() protoreflect.Message {
	mi := &file_feedback_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AverageStat.ProtoReflect.Descriptor instead.
func (*AverageStat) Descriptor() ([]byte, []int) {
	return file_feedback_service_proto_rawDescGZIP(), []int{1}
}

func (x *AverageStat) GetFeedbackId() string {
	if x != nil {
		return x.FeedbackId
	}
	return ""
}

func (x *AverageStat) GetAverage() float32 {
	if x != nil {
		return x.Average
	}
	return 0
}

type SaveFeedbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feedback      *Feedback              `protobuf:"bytes,1,opt,name=feedback,proto3" json:"feedback,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveFeedbackRequest) Reset() {
	*x = SaveFeedbackRequest{}
	mi := &file_feedback_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveFeedbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveFeedbackRequest) ProtoMessage() {}

func (x *SaveFeedbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feedback_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveFeedbackRequest.ProtoReflect.Descriptor instead.
func (*SaveFeedbackRequest) Descriptor() ([]byte, []int) {
	return file_feedback_service_proto_rawDescGZIP(), []int{2}
}

func (x *SaveFeedbackRequest) GetFeedback() *Feedback {
	if x != nil {
		return x.Feedback
	}
	return nil
}

type SaveFeedbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveFeedbackResponse) Reset() {
	*x = SaveFeedbackResponse{}
	mi := &file_feedback_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveFeedbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveFeedbackResponse) ProtoMessage() {}

func (x *SaveFeedbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feedback_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveFeedbackResponse.ProtoReflect.Descriptor instead.
func (*SaveFeedbackResponse) Descriptor() ([]byte, []int) {
	return file_feedback_service_proto_rawDescGZIP(), []int{3}
}

func (x *SaveFeedbackResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetAllFeedbackTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          FeedbackType           `protobuf:"varint,1,opt,name=type,proto3,enum=file_service.FeedbackType" json:"type,omitempty"`
	Ts            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=ts,proto3" json:"ts,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllFeedbackTypeRequest) Reset() {
	*x = GetAllFeedbackTypeRequest{}
	mi := &file_feedback_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllFeedbackTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllFeedbackTypeRequest) ProtoMessage() {}

func (x *GetAllFeedbackTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feedback_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllFeedbackTypeRequest.ProtoReflect.Descriptor instead.
func (*GetAllFeedbackTypeRequest) Descriptor() ([]byte, []int) {
	return file_feedback_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllFeedbackTypeRequest) GetType() FeedbackType {
	if x != nil {
		return x.Type
	}
	return FeedbackType_FEEDBACK_GENERAL
}

func (x *GetAllFeedbackTypeRequest) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *GetAllFeedbackTypeRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetAllFeedbackTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feedback      []*Feedback            `protobuf:"bytes,1,rep,name=feedback,proto3" json:"feedback,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllFeedbackTypeResponse) Reset() {
	*x = GetAllFeedbackTypeResponse{}
	mi := &file_feedback_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllFeedbackTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllFeedbackTypeResponse) ProtoMessage() {}

func (x *GetAllFeedbackTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feedback_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllFeedbackTypeResponse.ProtoReflect.Descriptor instead.
func (*GetAllFeedbackTypeResponse) Descriptor() ([]byte, []int) {
	return file_feedback_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetAllFeedbackTypeResponse) GetFeedback() []*Feedback {
	if x != nil {
		return x.Feedback
	}
	return nil
}

var File_feedback_service_proto protoreflect.FileDescriptor

const file_feedback_service_proto_rawDesc = "" +
	"\n" +
	"\x16feedback_service.proto\x12\ffile_service\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd6\x01\n" +
	"\bFeedback\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06rating\x18\x02 \x01(\x05R\x06rating\x12#\n" +
	"\rrespondent_id\x18\x03 \x01(\tR\frespondentId\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12.\n" +
	"\x04type\x18\x05 \x01(\x0e2\x1a.file_service.FeedbackTypeR\x04type\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"H\n" +
	"\vAverageStat\x12\x1f\n" +
	"\vfeedback_id\x18\x01 \x01(\tR\n" +
	"feedbackId\x12\x18\n" +
	"\aaverage\x18\x02 \x01(\x02R\aaverage\"I\n" +
	"\x13SaveFeedbackRequest\x122\n" +
	"\bfeedback\x18\x01 \x01(\v2\x16.file_service.FeedbackR\bfeedback\"0\n" +
	"\x14SaveFeedbackResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x8d\x01\n" +
	"\x19GetAllFeedbackTypeRequest\x12.\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1a.file_service.FeedbackTypeR\x04type\x12*\n" +
	"\x02ts\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"P\n" +
	"\x1aGetAllFeedbackTypeResponse\x122\n" +
	"\bfeedback\x18\x01 \x03(\v2\x16.file_service.FeedbackR\bfeedback*\x96\x01\n" +
	"\fFeedbackType\x12\x14\n" +
	"\x10FEEDBACK_GENERAL\x10\x00\x12\x11\n" +
	"\rFEEDBACK_POST\x10\x01\x12\x16\n" +
	"\x12FEEDBACK_MESSENGER\x10\x02\x12\x1c\n" +
	"\x18FEEDBACK_RECOMMENDATIONS\x10\x03\x12\x14\n" +
	"\x10FEEDBACK_PROFILE\x10\x04\x12\x11\n" +
	"\rFEEDBACK_AUTH\x10\x052\xd1\x01\n" +
	"\x0fFeedbackService\x12U\n" +
	"\fSaveFeedback\x12!.file_service.SaveFeedbackRequest\x1a\".file_service.SaveFeedbackResponse\x12g\n" +
	"\x12GetAllFeedbackType\x12'.file_service.GetAllFeedbackTypeRequest\x1a(.file_service.GetAllFeedbackTypeResponseB!Z\x1fquickflow/shared/proto/feedbackb\x06proto3"

var (
	file_feedback_service_proto_rawDescOnce sync.Once
	file_feedback_service_proto_rawDescData []byte
)

func file_feedback_service_proto_rawDescGZIP() []byte {
	file_feedback_service_proto_rawDescOnce.Do(func() {
		file_feedback_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_feedback_service_proto_rawDesc), len(file_feedback_service_proto_rawDesc)))
	})
	return file_feedback_service_proto_rawDescData
}

var file_feedback_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_feedback_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_feedback_service_proto_goTypes = []any{
	(FeedbackType)(0),                  // 0: file_service.FeedbackType
	(*Feedback)(nil),                   // 1: file_service.Feedback
	(*AverageStat)(nil),                // 2: file_service.AverageStat
	(*SaveFeedbackRequest)(nil),        // 3: file_service.SaveFeedbackRequest
	(*SaveFeedbackResponse)(nil),       // 4: file_service.SaveFeedbackResponse
	(*GetAllFeedbackTypeRequest)(nil),  // 5: file_service.GetAllFeedbackTypeRequest
	(*GetAllFeedbackTypeResponse)(nil), // 6: file_service.GetAllFeedbackTypeResponse
	(*timestamppb.Timestamp)(nil),      // 7: google.protobuf.Timestamp
}
var file_feedback_service_proto_depIdxs = []int32{
	0, // 0: file_service.Feedback.type:type_name -> file_service.FeedbackType
	7, // 1: file_service.Feedback.created_at:type_name -> google.protobuf.Timestamp
	1, // 2: file_service.SaveFeedbackRequest.feedback:type_name -> file_service.Feedback
	0, // 3: file_service.GetAllFeedbackTypeRequest.type:type_name -> file_service.FeedbackType
	7, // 4: file_service.GetAllFeedbackTypeRequest.ts:type_name -> google.protobuf.Timestamp
	1, // 5: file_service.GetAllFeedbackTypeResponse.feedback:type_name -> file_service.Feedback
	3, // 6: file_service.FeedbackService.SaveFeedback:input_type -> file_service.SaveFeedbackRequest
	5, // 7: file_service.FeedbackService.GetAllFeedbackType:input_type -> file_service.GetAllFeedbackTypeRequest
	4, // 8: file_service.FeedbackService.SaveFeedback:output_type -> file_service.SaveFeedbackResponse
	6, // 9: file_service.FeedbackService.GetAllFeedbackType:output_type -> file_service.GetAllFeedbackTypeResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_feedback_service_proto_init() }
func file_feedback_service_proto_init() {
	if File_feedback_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_feedback_service_proto_rawDesc), len(file_feedback_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_feedback_service_proto_goTypes,
		DependencyIndexes: file_feedback_service_proto_depIdxs,
		EnumInfos:         file_feedback_service_proto_enumTypes,
		MessageInfos:      file_feedback_service_proto_msgTypes,
	}.Build()
	File_feedback_service_proto = out.File
	file_feedback_service_proto_goTypes = nil
	file_feedback_service_proto_depIdxs = nil
}
