definitions:
  forms.AuthForm:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  forms.ErrorForm:
    properties:
      error:
        example: error message
        type: string
    type: object
  forms.PostOut:
    properties:
      comment_count:
        type: integer
      created_at:
        type: string
      creator_id:
        type: string
      id:
        type: string
      like_count:
        type: integer
      pics:
        items:
          type: string
        type: array
      repost_count:
        type: integer
      text:
        type: string
    type: object
  forms.SignUpForm:
    properties:
      birth_date:
        type: string
      firstname:
        type: string
      lastname:
        type: string
      password:
        type: string
      sex:
        type: integer
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/feed:
    get:
      description: Возвращает список постов, опубликованных до указанного времени
      parameters:
      - description: Количество постов
        in: query
        name: posts_count
        required: true
        type: integer
      - description: Временная метка
        in: query
        name: ts
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Список постов
          schema:
            items:
              $ref: '#/definitions/forms.PostOut'
            type: array
        "400":
          description: Некорректные данные
          schema:
            $ref: '#/definitions/forms.ErrorForm'
        "500":
          description: Ошибка сервера
          schema:
            $ref: '#/definitions/forms.ErrorForm'
      summary: Получить ленту
      tags:
      - Feed
  /api/hello:
    get:
      description: Проверяет доступность API, всегда возвращает "Hello, world!"
      produces:
      - application/json
      responses:
        "200":
          description: Hello, world!
          schema:
            type: string
      summary: Ping
      tags:
      - Misc
  /api/login:
    post:
      consumes:
      - application/json
      description: Аутентифицирует пользователя и устанавливает сессию
      parameters:
      - description: Данные для входа
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/forms.AuthForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Некорректные данные
          schema:
            $ref: '#/definitions/forms.ErrorForm'
        "401":
          description: Неверный логин или пароль
          schema:
            $ref: '#/definitions/forms.ErrorForm'
      summary: Авторизация
      tags:
      - Auth
  /api/logout:
    post:
      description: Удаляет сессию пользователя
      responses:
        "200":
          description: OK
          schema:
            type: string
        "401":
          description: Пользователь не авторизован
          schema:
            $ref: '#/definitions/forms.ErrorForm'
      summary: Выход из системы
      tags:
      - Auth
  /api/post:
    post:
      consumes:
      - multipart/form-data
      description: Добавляет новый пост в ленту
      parameters:
      - description: Текст поста
        in: formData
        name: text
        required: true
        type: string
      - description: Изображения
        in: formData
        name: pics
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Некорректные данные
          schema:
            $ref: '#/definitions/forms.ErrorForm'
        "500":
          description: Ошибка сервера
          schema:
            $ref: '#/definitions/forms.ErrorForm'
      summary: Добавить пост
      tags:
      - Feed
  /api/signup:
    post:
      consumes:
      - application/json
      description: Создает новую учетную запись пользователя
      parameters:
      - description: Данные для регистрации
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/forms.SignUpForm'
      produces:
      - application/json
      responses:
        "200":
          description: user_id нового пользователя
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Некорректные данные
          schema:
            $ref: '#/definitions/forms.ErrorForm'
        "409":
          description: Логин уже занят
          schema:
            $ref: '#/definitions/forms.ErrorForm'
      summary: Регистрация пользователя
      tags:
      - Auth
swagger: "2.0"
